### ISSUE TITLE
Incompatible with versions older than 1.19.2

### ISSUE THREAD

**Issue by EthanRStokes** [nvb-uy/Advanced-Movement#1]
Advanced Movement requires any version of the "fabric-api" mod but the change to go from "fabric" to "fabric-api" was only in 1.19.2 versions of FAPI
The dependency is unable to be met.

Solution: Change dependency from "fabric-api" to "fabric"
fabric api still provides the "fabric" mod id on 1.19.2 so it will still work

**Comment by nvb-uy** [comment]
Ah, I thought thay they've changed it for every version, I'll be using fabric then, and whenever they stop giving support for it I'll switch to it. Thanks!

**Comment by nvb-uy** [comment]
Hotfix uploaded:
https://www.curseforge.com/minecraft/mc-mods/advanced-movement/files/3944530
