### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [nvb-uy/Advanced-Movement#2]
**MC** 1.19.2
**QSL** 4.0.0 beta 9
**Advanced Movement** 22.08.20

The game crashes on startup with the mod installed. Affects Fabric as well.

Logs: https://gist.github.com/Footage2-Amply-Pounce/bc917f9e8e911dd57a662ad5659a0de8

**Comment by nvb-uy** [comment]
I'll look into it, it might be simply just using the wrong formatting. Weirdly enough I couldn't replicate it.

**Comment by nvb-uy** [comment]
Registry stuff, I think I've fixed it. The version I built had a comment on the registry but didn't have any in the annotations, do you mind testing the new hotfix (which will be released in a couple minutes) so I can mark this issue as resolved? ^^

**Comment by SplendidAlakey** [comment]
Sure! Still waiting for CurseForge, but I will test it as soon as it's up.

**Comment by SplendidAlakey** [comment]
The file appeared on CurseForge just now, timestamped as "42min ago", gotta love CF.

Anyways, the issue is fixed, thank you!
